[server]
port = 18443
enableCORS = true
sslCertFile = 'cert.pem'
sslKeyFile = 'key.pem'
baseUrlPath = 'weibo-plugin'

[browser]
serverAddress = "callfansai.cn"
gatherUsageStats = false

[runner]
magicEnabled = false